### PR TITLE
G13++ - and the kitchen sink...

### PR DESCRIPTION
**Pull request by james-fowler**
This is almost a rewrite - much of the original code is still there but it's been significantly refactored.  I've also added a whole lot of new features, including 

* Text output to the LCD
* Multiple Key / Key + modifier bindings
* Multiple profiles for key bindings - switch on the fly
* Adjustable STICK mode, and adjustable zones
* command line options, like ***sudo ./g13d --config starcraft2.bind --logo starcraft.lpbm***

and more...  /README.md covers most of it.

### CODE REVIEW

**Comment by ecraven** [comment]
thanks for this, sorry I've been unresponsive up until now. I'll have a look later and will probably merge this. thank you for all the hard work!

**Comment by james-fowler** [comment]
That's OK, I hadn't really expected much until I put in a pull request, and you responded to that plenty quick.  

As I mentioned, there are a LOT of new features, and I took quite a bit of liberty in reorganizing the code - partly because it makes it much easier to extend cleanly (the number of lines of C++ source more than doubled, and that's after shortening several parts of the original code).   I have informally tested just about everything I can think of, except for managing multiple G-13s (I only have one, but theoretically it looks possible...).

Even where I've extended things, I've tried to keep the usage completely backwards compatible, so that existing users should be able to drop this in and have it just work.  For example:
* launching **sudo ./g13d mylogo.lpbm** still works the same, even with the new command line arguments
* bind key targets no longer need *KEY_*, for example ***bind G1 LEFTCTRL+F1*** works, but ***bind G1 KEY_F1*** also still works
* **bind STICK_*****direction key*** still works, although **stick_zone action** ***zonename key*** might be preferred.

The only negative I've noticed compared to the original is that the resulting executable is larger (grew from around 337k to 709k on my system) and it probably uses more heap space too.  That doesn't bother me, but I'm running on a system with 32GB ram so YMMV...

There are a still a few things I'd like to see added, including better logging and better handling of device permissions.  Fortunately much of that's already been done in the pull requests by @thecarp(#3) and @lmiphay(#11).

Check it out, if you like it you might consider [adding me as a collaborator](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/).  That way I could help manage issues and pull requests.

**Comment by ecraven** [comment]
Sorry, a bit tight on time right now, I've added you as a collaborator,
feel free to use that power :)

Basically the direction I was aiming for is no gui, but a daemon that
can be instructed via the pipe (or command-line arguments).

Thanks for all your hard work!

Greetings, Peter

**Comment by james-fowler** [comment]
Thanks!  I'll put it to good use... although it may be a little slow 
through the holidays.

- James

**Pull request merged**
